### ISSUE TITLE
[Themes] -- Fix CSS when switching between light/dark themes

### ISSUE THREAD

**Issue by irwin-nikk** [invainn/ARIA#103]
Currently, certain CSS elements do not reflect the two themes in ARIA. 

1. The themes need to be updated so that they properly propagate CSS styling for all elements.

**Comment by invainn** [comment]
#149 

Will fix other issue later

**Comment by irwin-nikk** [comment]
This issue has been resolved by Anthony and myself. A fix for the page headings has been found.
