### ISSUE TITLE
[Feb. 22nd Demo] -- Admin Portal, Create an Event

### ISSUE THREAD

**Issue by irwin-nikk** [invainn/ARIA#131]
Update the CSS so that each field is spaced out better (use padding and margins). Add additional fields for the amount of levels, the level names, the cost, etc. (review the old aria admin portal for the rest of the required fields).

**Comment by Kevin-Carlos** [comment]
Done.

**Comment by irwin-nikk** [comment]
If the issue is complete please refer to it using the hash-symbol in your pull-request and close the issue.

**Comment by irwin-nikk** [comment]
Wait until @invainn merges your pull-request before closing this issue.

**Comment by irwin-nikk** [comment]
not done noob.

**Comment by Kevin-Carlos** [comment]
TODO: Create a stepper and split up the steps to create an event, otherwise for now, *DONE*

**Comment by irwin-nikk** [comment]
Closing this issue. Create a new issue for the stepper it wasn't required for the demo.
