### ISSUE TITLE
[Feb. 22nd Demo] -- Customer/Teacher Portals, Active Registrations/Student Registrations

### ISSUE THREAD

**Issue by irwin-nikk** [invainn/ARIA#134]
Along with the existing data that is shown when a user is selected, the following fields should be added for Song 1, Song 2, and Song 3

1. Period: 
2. Composer: 
3. Piece:

**Comment by Kevin-Carlos** [comment]
Customer portal: Needs to have data created to take in composer and period.
Need to do the teacher portal.

**Comment by irwin-nikk** [comment]
Closing this issue. Kevin has implemented this. It may need updated styling later for greater readability.
