### ISSUE TITLE
[Feb. 22nd Demo] -- Customer Portal, Register for an Event

### ISSUE THREAD

**Issue by irwin-nikk** [invainn/ARIA#137]
Add a new stepper option called "Command Performance Options" where a customer will select the day/time they would prefer their child to play in a command performance, assuming they are selected for their distinction in an event.

**Comment by Kevin-Carlos** [comment]
Done.

**Comment by irwin-nikk** [comment]
This issue has been completed by Kevin. Closing this issue.
