### ISSUE TITLE
[Admin Portal] Create an Event

### ISSUE THREAD

**Issue by Kevin-Carlos** [invainn/ARIA#147]
Create a stepper and split up the process of creating an event. The current implementation is ugly and introduces an eyesore.

**Comment by irwin-nikk** [comment]
LOL, the imagery in this issue description is flawless.

**Comment by irwin-nikk** [comment]
Kevin has completed the stepper requirements, however, we need to fix the CSS for the button placement.

**Comment by irwin-nikk** [comment]
Initial version completed.
