### ISSUE TITLE
[Admin Portal] -- Make Cards & Drawer Tabs Uniform

### ISSUE THREAD

**Issue by irwin-nikk** [invainn/ARIA#152]
The drawer tabs and cards do not have uniform icons or titles, this needs to be fixed.

**Comment by invainn** [comment]
@irwin-nikk if PR #166 fixes this issue, please close or describe in more detail, thank you!

**Comment by irwin-nikk** [comment]
@invainn I need to make final checks on this issue. I will take responsibility for it and close it before the April 19th demo with Dr. Harris.

**Comment by irwin-nikk** [comment]
This issue was completed by @irwin-nikk and @invainn.
