### ISSUE TITLE
AccountFields should be renamed to something more generic

### ISSUE THREAD

**Issue by invainn** [invainn/ARIA#39]
It's currently being used by more than one component so it should be renamed to something more generic and placed outside of CustomerPortal.

**Comment by irwin-nikk** [comment]
I’m not sure this makes sense. The AccountFields component is part of the MyAccount tab of the Customer Portal drawer. Why would we place it outside the portal?

**Comment by irwin-nikk** [comment]
This issue has been rewritten as part of issue #97 with greater clarification. It will be addressed there.
